<?php
if ( ! defined( 'ABSPATH' ) ) exit;

function wlg_get_countries() {
	return array(
		// ── América Latina ──
		array( 'flag' => '🇦🇷', 'name' => 'Argentina',             'dial' => '54' ),
		array( 'flag' => '🇧🇴', 'name' => 'Bolivia',               'dial' => '591' ),
		array( 'flag' => '🇧🇷', 'name' => 'Brasil',                'dial' => '55' ),
		array( 'flag' => '🇨🇱', 'name' => 'Chile',                 'dial' => '56' ),
		array( 'flag' => '🇨🇴', 'name' => 'Colombia',              'dial' => '57' ),
		array( 'flag' => '🇨🇷', 'name' => 'Costa Rica',            'dial' => '506' ),
		array( 'flag' => '🇨🇺', 'name' => 'Cuba',                  'dial' => '53' ),
		array( 'flag' => '🇩🇴', 'name' => 'República Dominicana',  'dial' => '1809' ),
		array( 'flag' => '🇪🇨', 'name' => 'Ecuador',               'dial' => '593' ),
		array( 'flag' => '🇸🇻', 'name' => 'El Salvador',           'dial' => '503' ),
		array( 'flag' => '🇬🇹', 'name' => 'Guatemala',             'dial' => '502' ),
		array( 'flag' => '🇭🇳', 'name' => 'Honduras',              'dial' => '504' ),
		array( 'flag' => '🇯🇲', 'name' => 'Jamaica',               'dial' => '1876' ),
		array( 'flag' => '🇲🇽', 'name' => 'México',                'dial' => '52' ),
		array( 'flag' => '🇳🇮', 'name' => 'Nicaragua',             'dial' => '505' ),
		array( 'flag' => '🇵🇦', 'name' => 'Panamá',                'dial' => '507' ),
		array( 'flag' => '🇵🇾', 'name' => 'Paraguay',              'dial' => '595' ),
		array( 'flag' => '🇵🇪', 'name' => 'Perú',                  'dial' => '51' ),
		array( 'flag' => '🇵🇷', 'name' => 'Puerto Rico',           'dial' => '1787' ),
		array( 'flag' => '🇺🇾', 'name' => 'Uruguay',               'dial' => '598' ),
		array( 'flag' => '🇻🇪', 'name' => 'Venezuela',             'dial' => '58' ),
		// ── América del Norte ──
		array( 'flag' => '🇺🇸', 'name' => 'Estados Unidos',        'dial' => '1' ),
		array( 'flag' => '🇨🇦', 'name' => 'Canadá',                'dial' => '1' ),
		// ── Europa ──
		array( 'flag' => '🇩🇪', 'name' => 'Alemania',              'dial' => '49' ),
		array( 'flag' => '🇦🇹', 'name' => 'Austria',               'dial' => '43' ),
		array( 'flag' => '🇧🇪', 'name' => 'Bélgica',               'dial' => '32' ),
		array( 'flag' => '🇩🇰', 'name' => 'Dinamarca',             'dial' => '45' ),
		array( 'flag' => '🇪🇸', 'name' => 'España',                'dial' => '34' ),
		array( 'flag' => '🇫🇮', 'name' => 'Finlandia',             'dial' => '358' ),
		array( 'flag' => '🇫🇷', 'name' => 'Francia',               'dial' => '33' ),
		array( 'flag' => '🇬🇷', 'name' => 'Grecia',                'dial' => '30' ),
		array( 'flag' => '🇮🇪', 'name' => 'Irlanda',               'dial' => '353' ),
		array( 'flag' => '🇮🇹', 'name' => 'Italia',                'dial' => '39' ),
		array( 'flag' => '🇳🇴', 'name' => 'Noruega',               'dial' => '47' ),
		array( 'flag' => '🇳🇱', 'name' => 'Países Bajos',          'dial' => '31' ),
		array( 'flag' => '🇵🇱', 'name' => 'Polonia',               'dial' => '48' ),
		array( 'flag' => '🇵🇹', 'name' => 'Portugal',              'dial' => '351' ),
		array( 'flag' => '🇬🇧', 'name' => 'Reino Unido',           'dial' => '44' ),
		array( 'flag' => '🇷🇺', 'name' => 'Rusia',                 'dial' => '7' ),
		array( 'flag' => '🇸🇪', 'name' => 'Suecia',                'dial' => '46' ),
		array( 'flag' => '🇨🇭', 'name' => 'Suiza',                 'dial' => '41' ),
		array( 'flag' => '🇺🇦', 'name' => 'Ucrania',               'dial' => '380' ),
		// ── Asia / Pacífico ──
		array( 'flag' => '🇸🇦', 'name' => 'Arabia Saudita',        'dial' => '966' ),
		array( 'flag' => '🇦🇺', 'name' => 'Australia',             'dial' => '61' ),
		array( 'flag' => '🇨🇳', 'name' => 'China',                 'dial' => '86' ),
		array( 'flag' => '🇰🇷', 'name' => 'Corea del Sur',         'dial' => '82' ),
		array( 'flag' => '🇦🇪', 'name' => 'Emiratos Árabes',       'dial' => '971' ),
		array( 'flag' => '🇵🇭', 'name' => 'Filipinas',             'dial' => '63' ),
		array( 'flag' => '🇮🇳', 'name' => 'India',                 'dial' => '91' ),
		array( 'flag' => '🇮🇱', 'name' => 'Israel',                'dial' => '972' ),
		array( 'flag' => '🇯🇵', 'name' => 'Japón',                 'dial' => '81' ),
		array( 'flag' => '🇲🇾', 'name' => 'Malasia',               'dial' => '60' ),
		array( 'flag' => '🇲🇽', 'name' => 'Marruecos',             'dial' => '212' ),
		array( 'flag' => '🇳🇿', 'name' => 'Nueva Zelanda',         'dial' => '64' ),
		array( 'flag' => '🇵🇰', 'name' => 'Pakistán',              'dial' => '92' ),
		array( 'flag' => '🇸🇬', 'name' => 'Singapur',              'dial' => '65' ),
		array( 'flag' => '🇹🇷', 'name' => 'Turquía',               'dial' => '90' ),
		// ── África ──
		array( 'flag' => '🇳🇬', 'name' => 'Nigeria',               'dial' => '234' ),
		array( 'flag' => '🇿🇦', 'name' => 'Sudáfrica',             'dial' => '27' ),
	);
}
